### ISSUE TITLE
Allow CSP Support

### ISSUE THREAD

**Issue by robinboehm** [goinstant/goangular#14]
I've tried to create a Chrome Ext that use GoInstant.
In this context, some kind of pattern's are forbidden like generating functions.

If I try to boot my Chrome Ext with goAngular, I got this message in the console:

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 goangular.js:2950

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 goangular.js:2950

Refs:
Angular CSP Mode: http://docs.angularjs.org/api/ng.directive:ngCsp
CSP https://developer.mozilla.org/en/Security/CSP

Would be cool if you add CSP support - I've many ideas how to create great things with goInstant in a Chrome Ext. ;)

Rob

**Comment by mattcreager** [comment]
Thanks Rob, I'm busy hacking away on the user management module, exploring this is next up :)

**Comment by robinboehm** [comment]
Oki - may I'll fix it and create an PR

**Comment by mattcreager** [comment]
Confirmed this bug is resolved, let me know if you have any other issues :)
