### ISSUE TITLE
Users Implementation

### ISSUE THREAD

**Issue by mattcreager** [goinstant/goangular#18]
Users will be a convenience method for `key('/.users')`:

``` js
angularApp.controller('Ctrl', function($scope, goConnection) {
  var connectionPromise = goConnection.ready();

  connectionPromise.then(function() {
    var lobby = goConnection.room('lobby');  // lobby is joined by default
    var usersPromise = lobby.users.get();  // Returns a promise

    usersPromise.then(function(userObj) {
      // You have your users object
    }).finally($scope.$apply);
  });
});
```

**Comment by robinboehm** [comment]
Why the API defines:
I) room('lobby') & lobby.users.get()

and not:
II) room('lobby') & lobby.users()

or:
III) room('lobby').get() & lobby.users.get()?

Inconsistent API here?
I would prefer option II).

**Comment by mattcreager** [comment]
I'd propose we first align with the GoInstant [Room](https://developers.goinstant.com/v1/javascript_api/rooms/index.html#room.users) API:

``` js
var usersKey = lobby.users; // users is just a convenience method for key('/.users')

usersKey.get().then(function...  
```

and perhaps then design a higher level API providing access directly to users via. a service?

**Comment by mattcreager** [comment]
This change has been made redundant by the introduction of promises to the GoInstant API!
