### ISSUE TITLE
model#set merges new value into model

### ISSUE THREAD

**Issue by colinmacdonald** [goinstant/goangular#52]
``` js
$scope.results = $goKey('results').$sync();

$scope.results.$set({ a: 1}, {b: 2});
```

At this point all is well, $scope.results has `a: 1` and `b: 2`.

``` js
$scope.results.$set({ a: 11 });
```

I would expect this to overwrite everything currently in that model, instead it merges the new value of a. Now the model has both `a: 11` and `b: 2` instead of just `a: 11`.

Upon refreshing the page, the model syncs and is correct again with just `a: 11`.

**Comment by mattcreager** [comment]
Joining.

**Comment by mattcreager** [comment]
I've fixed the issue but we'll need regression tests in the next release.  Nice catch :)

**Comment by mattcreager** [comment]
Leaving.
