### ISSUE TITLE
GoAngular homepage typo - "text/javacript" 

### ISSUE THREAD

**Issue by YoDK** [goinstant/goangular#68]
https://developers.goinstant.com/v1/GoAngular/index.html

![](http://dl.dropbox.com/u/113049/Screenshots/djwthx08f8m8.png)

**Comment by YoDK** [comment]
For some reason this didn't work. Re-opening

**Comment by YoDK** [comment]
![](http://dl.dropbox.com/u/113049/Screenshots/gfqbjyt5gses.png)

**Comment by mattcreager** [comment]
Confirmed resolved in develop.
